name: Build and Push Docker Images

on:
    push:
        branches:
            - main
        tags:
            - "v*.*.*"
    workflow_dispatch:

env:
    # Docker Hub org/user. Set DOCKERHUB_USERNAME in repo secrets.
    DOCKERHUB_REPO_UI: ${{ secrets.DOCKERHUB_USERNAME }}/ui
    DOCKERHUB_REPO_STRAPI: ${{ secrets.DOCKERHUB_USERNAME }}/strapi

jobs:
    docker:
        name: Build & Push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: ui
                      context: .
                      dockerfile: apps/ui/Dockerfile
                      image: ${{ secrets.DOCKERHUB_USERNAME }}/ui
                      build-args: |
                          APP_PUBLIC_URL=${{ secrets.UI_APP_PUBLIC_URL }}
                          STRAPI_URL=${{ secrets.UI_STRAPI_URL }}
                          STRAPI_REST_READONLY_API_KEY=${{ secrets.UI_STRAPI_REST_READONLY_API_KEY }}
                    - name: strapi
                      context: .
                      dockerfile: apps/strapi/Dockerfile
                      image: ${{ secrets.DOCKERHUB_USERNAME }}/strapi
                      build-args: |
                          # Strapi build typically only needs NODE_ENV. Runtime envs come from deployment.
                          NODE_ENV=production

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract tags
              id: meta
              run: |
                  # Compute version and tags
                  SHA_TAG=${GITHUB_SHA::7}
                  BRANCH=${GITHUB_REF_NAME}
                  TAGS="${{ matrix.image }}:sha-${SHA_TAG}"
                  if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
                    TAGS+=",${{ matrix.image }}:latest"
                  fi
                  if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
                    VERSION_TAG=${GITHUB_REF_NAME}
                    TAGS+=",${{ matrix.image }}:${VERSION_TAG}"
                  fi
                  echo "tags=${TAGS}" >> $GITHUB_OUTPUT

            - name: Build and push ${{ matrix.name }}
              uses: docker/build-push-action@v6
              with:
                  context: ${{ matrix.context }}
                  file: ${{ matrix.dockerfile }}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  platforms: linux/amd64
                  build-args: ${{ matrix.build-args }}
                  cache-from: type=registry,ref=${{ matrix.image }}:buildcache
                  cache-to: type=registry,ref=${{ matrix.image }}:buildcache,mode=max
